image: szdc/ubuntu-node-lts

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

before_script:
  - export NVM_DIR="/root/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - yarn install

stages:
  - analyse
  - build

lint:
  stage: analyse
  script:
    - make lint

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
